### ISSUE TITLE
Use a choices set for Question.kind

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/automated-survey-django#10]
This should be our last issue:

Testing the app on Heroku today, I spotted the `kind` field on the `Question` model. Right now it's a CharField but it looks like you're expecting only a small set of values:

- voice
- numeric
- yes-no

We should modify `Question.kind` to use a `choices` attribute instead. That way when devs are playing around in the admin, we'll save them from making a typo.

**Choices docs:** https://docs.djangoproject.com/en/1.8/ref/models/fields/#choices

**Comment by jsantos17** [comment]
Addressed by 3019fbdc05a142f0dc69aaa037a3fa385d00aae6

**Comment by atbaker** [comment]
Sweet - looks good.

I'm not sure if it was necessary, but I ran `makemigrations` again and it did pop out another migration file, so I added that in https://github.com/TwilioDevEd/automated-survey-django/commit/92edbd50034afd825a46a0421f29bc2304c8bb0e

Thanks!
