### ISSUE TITLE
Initial migrate: ValueError: <Question: what type... instance isn't saved

### ISSUE THREAD

**Issue by ama4tf** [TwilioDevEd/automated-survey-django#11]
I set up this project on a windows 7 server running Python 3.4. It took me a little while to get the packages set up but when I try to run migrate it won't load the sample questions (although it did set up the tables correctly). Instead it gives the error attached.

![rdcman_2016-03-10_15-00-42](https://cloud.githubusercontent.com/assets/5315159/13682697/f4bdc5fc-e6d0-11e5-910d-58776e30d9b3.png)

**Comment by shyba** [comment]
@ama4tf Hey, sorry for the delay on getting back to this issue.

This tutorial was being refactored and new features were added, now it is possible to answer the survey over SMS as well. We ended up modifying a lot of the code.
Would you mind to try again?
