### ISSUE TITLE
Add a data migration to load the sample survey data

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/automated-survey-django#2]
I really like that this app comes with a sample survey. I might add some sample data to the call-tracking-django repo also.

When reviewing tutorial code, I'm always looking for ways to reduce the number of commands a developer has to run to use our project.

The `load_survey` management command is useful, but right now a developer has to run it as a separate command after they migrate the database. It would be better if we could load that data for them automatically as part of a data migration.

See the Django docs for an example: https://docs.djangoproject.com/en/1.8/topics/migrations/#data-migrations

By adding a data migration after your other migrations, we can automatically load the sample survey into the database for our developers.

If you like, you can just have your data migration invoke your `load_survey` management command using `call_command`: https://docs.djangoproject.com/en/1.8/ref/django-admin/#running-management-commands-from-your-code

**Comment by jsantos17** [comment]
@atbaker I have added the data migration with 510f92c4526113, but I had to make data loading conditional on the running environment since the tests expect an empty database (as they should) so the tests fail when the database is not clean. Instead of a data migration I'd rather hook into the app initialization and insert the data there. I usually try to keep migrations schema-only.

**Comment by atbaker** [comment]
Hmm. I agree that running the tests off an empty database is ideal.

How were you thinking about loading the data in during app initialization? I've never found a good way of doing it with Django.

**Comment by jsantos17** [comment]
I think the current workaround works fine. I was going to add some code in the wsgi module but that sounds like a bad idea now. The app might not have started yet.

**Comment by atbaker** [comment]
Okay - cool. I'll close out this issue.
