### ISSUE TITLE
Remove django-environ from settings and requirements

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/automated-survey-django#4]
django-environ is a good library for managing difference between development environments, but I find it overkill for our sample apps.

Please remove it and just use normal `os.environ.get()` when you need to find environment variables.

You can reference the call-tracking-django settings for more examples: https://github.com/TwilioDevEd/call-tracking-django/tree/master/twilio_sample_project/settings

**Comment by jsantos17** [comment]
I rely on it to load the `.env` file and to parse the database URL. [python-dotenv](https://github.com/theskumar/python-dotenv) is broken. I'd rather avoid reinventing the wheel. Also, Kevin approved it when I first started development (you can find it HipChat history). But I can remove it if you want.

**Comment by atbaker** [comment]
Okay - then let's stick with django-environ for this app.

I'll do some research to see what the best solution is going forward. We'll definitely have a clear choice for how we want to handle this before you start the next Django app.
