### ISSUE TITLE
Avoid error after first time setup

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/automated-survey-django#5]
Right now when a developer sets up the app locally, they'll go to http://localhost:8000, get redirected to `/automated_survey`, and get a 500 error because there are no results in the system.

We want developers to know when they try to access the site for the first time that they configured the app correctly. To fix this, I would adjust the `/automated_survey` view and template to display some content that says "No survey data yet".

**Comment by jsantos17** [comment]
Adding the data migration you suggested would do this.

**Comment by atbaker** [comment]
Beautiful! Closing this issue.
