### ISSUE TITLE
Change simple class-based views to functional views

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/automated-survey-django#7]
Unlike with Flask, few people use class-based views in Django, instead opting for functional views.

Your `QuestionResponseView` is a big view, so I think it's good that it's a class-based view with helper methods.

Some other views are simpler, though, and should just be normal function-based views that Django developers will understand more easily:

- `QuestionView`
- `SurveyView`
- `SurveyResultsView`

These views are better off looking like `redirect_to_first_survey` - functions that return their response.

**Comment by jsantos17** [comment]
Addressed by 464b457e
