### ISSUE TITLE
README webhooks section needs to use a trailing slash - or use APPEND_SLASH=False

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/automated-survey-django#8]
When I set up the app for the first time, my Twilio calls would error because I had configured my number to point to `/first_survey` instead of `/first_survey/`.

Django error'd because by default it tries to append a slash to inbound requests, but it can't do that on a POST request without the browser dropping the data.

So we need to either update the instructions to include the trailing slash, or change the `APPEND_SLASH` setting to `False`.

https://docs.djangoproject.com/en/1.8/ref/settings/#append-slash

**Comment by jsantos17** [comment]
I definitely need to update the tutorial. The images are wrong as well. I'll update that soon.

**Comment by jsantos17** [comment]
README has been updated.

**Comment by atbaker** [comment]
Great - thank you. I just updated fixed a couple more references to it in the README also: https://github.com/TwilioDevEd/automated-survey-django/commit/122acd6cf8dd57c5416f11996516102e025a793f

So I think we're all good on this one.
