### ISSUE TITLE
Add an admin.py file to wire up your models with the Django admin

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/automated-survey-django#9]
This one's easy - just add an `admin.py` module ([like this one](https://github.com/TwilioDevEd/call-tracking-django/blob/master/call_tracking/admin.py)) so that developers can easily change the data that's in the system.

You might need to add a `__str__` method to your `Survey` and `QuestionResponse` models to get them to show up.

**Comment by jsantos17** [comment]
Done with 5157e639 and 61c3413c. Admin works fine now.

**Comment by atbaker** [comment]
Looks good to me! Thanks!
